<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>F1Net.Auth</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="5.8.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="5.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\F1Net.Application\F1Net.Application.csproj" />
    <ProjectReference Include="..\F1Net.Infrastructure\F1Net.Infrastructure.csproj" />
  </ItemGroup>
</Project>
